#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
#
Name     : irrlichtmt
Version  : 1.9.0mt10
Release  : 4
URL      : https://github.com/minetest/irrlicht/archive/refs/tags/1.9.0mt10.tar.gz
Source0  : https://github.com/minetest/irrlicht/archive/refs/tags/1.9.0mt10.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Zlib
Requires: irrlichtmt-lib = %{version}-%{release}
Requires: irrlichtmt-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : libX11-dev libICE-dev libSM-dev libXau-dev libXcomposite-dev libXcursor-dev libXdamage-dev libXdmcp-dev libXext-dev libXfixes-dev libXft-dev libXi-dev libXinerama-dev libXi-dev libXmu-dev libXpm-dev libXrandr-dev libXrender-dev libXres-dev libXScrnSaver-dev libXt-dev libXtst-dev libXv-dev libXxf86vm-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : libpng-dev
BuildRequires : mesa-dev
BuildRequires : zlib-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
IrrlichtMt version 1.9
======================
The Irrlicht Engine is an open source realtime 3D engine written in C++.

%package dev
Summary: dev components for the irrlichtmt package.
Group: Development
Requires: irrlichtmt-lib = %{version}-%{release}
Provides: irrlichtmt-devel = %{version}-%{release}
Requires: irrlichtmt = %{version}-%{release}

%description dev
dev components for the irrlichtmt package.


%package lib
Summary: lib components for the irrlichtmt package.
Group: Libraries
Requires: irrlichtmt-license = %{version}-%{release}

%description lib
lib components for the irrlichtmt package.


%package license
Summary: license components for the irrlichtmt package.
Group: Default

%description license
license components for the irrlichtmt package.


%prep
%setup -q -n irrlicht-1.9.0mt10
cd %{_builddir}/irrlicht-1.9.0mt10

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1681342934
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1681342934
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/irrlichtmt
cp %{_builddir}/irrlicht-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/irrlichtmt/bcbd5fcde0d5d5a7a0e6729f024dec58d6f48777 || :
cp %{_builddir}/irrlicht-%{version}/doc/irrlicht-license.txt %{buildroot}/usr/share/package-licenses/irrlichtmt/bcbd5fcde0d5d5a7a0e6729f024dec58d6f48777 || :
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/irrlichtmt/CIndexBuffer.h
/usr/include/irrlichtmt/CMeshBuffer.h
/usr/include/irrlichtmt/CVertexBuffer.h
/usr/include/irrlichtmt/EAttributes.h
/usr/include/irrlichtmt/ECullingTypes.h
/usr/include/irrlichtmt/EDebugSceneTypes.h
/usr/include/irrlichtmt/EDeviceTypes.h
/usr/include/irrlichtmt/EDriverFeatures.h
/usr/include/irrlichtmt/EDriverTypes.h
/usr/include/irrlichtmt/EFocusFlags.h
/usr/include/irrlichtmt/EGUIAlignment.h
/usr/include/irrlichtmt/EGUIElementTypes.h
/usr/include/irrlichtmt/EHardwareBufferFlags.h
/usr/include/irrlichtmt/EMaterialFlags.h
/usr/include/irrlichtmt/EMaterialTypes.h
/usr/include/irrlichtmt/EMeshWriterEnums.h
/usr/include/irrlichtmt/EPrimitiveTypes.h
/usr/include/irrlichtmt/EReadFileType.h
/usr/include/irrlichtmt/ESceneNodeTypes.h
/usr/include/irrlichtmt/EShaderTypes.h
/usr/include/irrlichtmt/EVertexAttributes.h
/usr/include/irrlichtmt/IAnimatedMesh.h
/usr/include/irrlichtmt/IAnimatedMeshSceneNode.h
/usr/include/irrlichtmt/IAttributes.h
/usr/include/irrlichtmt/IBillboardSceneNode.h
/usr/include/irrlichtmt/IBoneSceneNode.h
/usr/include/irrlichtmt/ICameraSceneNode.h
/usr/include/irrlichtmt/IContextManager.h
/usr/include/irrlichtmt/ICursorControl.h
/usr/include/irrlichtmt/IDummyTransformationSceneNode.h
/usr/include/irrlichtmt/IEventReceiver.h
/usr/include/irrlichtmt/IFileArchive.h
/usr/include/irrlichtmt/IFileList.h
/usr/include/irrlichtmt/IFileSystem.h
/usr/include/irrlichtmt/IGPUProgrammingServices.h
/usr/include/irrlichtmt/IGUIButton.h
/usr/include/irrlichtmt/IGUICheckBox.h
/usr/include/irrlichtmt/IGUIComboBox.h
/usr/include/irrlichtmt/IGUIEditBox.h
/usr/include/irrlichtmt/IGUIElement.h
/usr/include/irrlichtmt/IGUIEnvironment.h
/usr/include/irrlichtmt/IGUIFileOpenDialog.h
/usr/include/irrlichtmt/IGUIFont.h
/usr/include/irrlichtmt/IGUIFontBitmap.h
/usr/include/irrlichtmt/IGUIImage.h
/usr/include/irrlichtmt/IGUIImageList.h
/usr/include/irrlichtmt/IGUIListBox.h
/usr/include/irrlichtmt/IGUIScrollBar.h
/usr/include/irrlichtmt/IGUISkin.h
/usr/include/irrlichtmt/IGUISpriteBank.h
/usr/include/irrlichtmt/IGUIStaticText.h
/usr/include/irrlichtmt/IGUITabControl.h
/usr/include/irrlichtmt/IGUIToolbar.h
/usr/include/irrlichtmt/IImage.h
/usr/include/irrlichtmt/IImageLoader.h
/usr/include/irrlichtmt/IImageWriter.h
/usr/include/irrlichtmt/IIndexBuffer.h
/usr/include/irrlichtmt/ILogger.h
/usr/include/irrlichtmt/IMaterialRenderer.h
/usr/include/irrlichtmt/IMaterialRendererServices.h
/usr/include/irrlichtmt/IMemoryReadFile.h
/usr/include/irrlichtmt/IMesh.h
/usr/include/irrlichtmt/IMeshBuffer.h
/usr/include/irrlichtmt/IMeshCache.h
/usr/include/irrlichtmt/IMeshLoader.h
/usr/include/irrlichtmt/IMeshManipulator.h
/usr/include/irrlichtmt/IMeshSceneNode.h
/usr/include/irrlichtmt/IMeshWriter.h
/usr/include/irrlichtmt/IOSOperator.h
/usr/include/irrlichtmt/IReadFile.h
/usr/include/irrlichtmt/IReferenceCounted.h
/usr/include/irrlichtmt/IRenderTarget.h
/usr/include/irrlichtmt/ISceneCollisionManager.h
/usr/include/irrlichtmt/ISceneManager.h
/usr/include/irrlichtmt/ISceneNode.h
/usr/include/irrlichtmt/IShaderConstantSetCallBack.h
/usr/include/irrlichtmt/ISkinnedMesh.h
/usr/include/irrlichtmt/ITexture.h
/usr/include/irrlichtmt/ITimer.h
/usr/include/irrlichtmt/IVertexBuffer.h
/usr/include/irrlichtmt/IVideoDriver.h
/usr/include/irrlichtmt/IWriteFile.h
/usr/include/irrlichtmt/IrrCompileConfig.h
/usr/include/irrlichtmt/IrrlichtDevice.h
/usr/include/irrlichtmt/Keycodes.h
/usr/include/irrlichtmt/S3DVertex.h
/usr/include/irrlichtmt/SAnimatedMesh.h
/usr/include/irrlichtmt/SColor.h
/usr/include/irrlichtmt/SExposedVideoData.h
/usr/include/irrlichtmt/SIrrCreationParameters.h
/usr/include/irrlichtmt/SMaterial.h
/usr/include/irrlichtmt/SMaterialLayer.h
/usr/include/irrlichtmt/SMesh.h
/usr/include/irrlichtmt/SMeshBuffer.h
/usr/include/irrlichtmt/SOverrideMaterial.h
/usr/include/irrlichtmt/SSkinMeshBuffer.h
/usr/include/irrlichtmt/SVertexIndex.h
/usr/include/irrlichtmt/SVertexManipulator.h
/usr/include/irrlichtmt/SViewFrustum.h
/usr/include/irrlichtmt/SceneParameters.h
/usr/include/irrlichtmt/aabbox3d.h
/usr/include/irrlichtmt/coreutil.h
/usr/include/irrlichtmt/dimension2d.h
/usr/include/irrlichtmt/exampleHelper.h
/usr/include/irrlichtmt/fast_atof.h
/usr/include/irrlichtmt/irrArray.h
/usr/include/irrlichtmt/irrMath.h
/usr/include/irrlichtmt/irrString.h
/usr/include/irrlichtmt/irrTypes.h
/usr/include/irrlichtmt/irrUString.h
/usr/include/irrlichtmt/irrlicht.h
/usr/include/irrlichtmt/irrpack.h
/usr/include/irrlichtmt/irrunpack.h
/usr/include/irrlichtmt/line2d.h
/usr/include/irrlichtmt/line3d.h
/usr/include/irrlichtmt/matrix4.h
/usr/include/irrlichtmt/mt_opengl.h
/usr/include/irrlichtmt/path.h
/usr/include/irrlichtmt/plane3d.h
/usr/include/irrlichtmt/position2d.h
/usr/include/irrlichtmt/quaternion.h
/usr/include/irrlichtmt/rect.h
/usr/include/irrlichtmt/triangle3d.h
/usr/include/irrlichtmt/vector2d.h
/usr/include/irrlichtmt/vector3d.h
/usr/lib64/cmake/IrrlichtMt/IrrlichtMtConfig.cmake
/usr/lib64/cmake/IrrlichtMt/IrrlichtMtConfigVersion.cmake
/usr/lib64/cmake/IrrlichtMt/IrrlichtMtTargets-relwithdebinfo.cmake
/usr/lib64/cmake/IrrlichtMt/IrrlichtMtTargets.cmake
/usr/lib64/libIrrlichtMt.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libIrrlichtMt.so.1.9.0.10

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/irrlichtmt/bcbd5fcde0d5d5a7a0e6729f024dec58d6f48777
